/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VIEW.PAINEIS;

import DAO.UsuarioDAO;
import javax.swing.JOptionPane;

/**
 *
 * @author Danilo
 */
public class PainelTrocarSenha extends javax.swing.JPanel {

    boolean senhacerta = false;

    /**
     * Creates new form PainelConta
     */
    public PainelTrocarSenha() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        senha1 = new javax.swing.JPasswordField();
        senha2 = new javax.swing.JPasswordField();
        msg = new javax.swing.JLabel();
        txtsenhaatual = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 152, 0));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        senha1.setBackground(new java.awt.Color(255, 152, 0));
        senha1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        senha1.setForeground(new java.awt.Color(255, 255, 255));
        senha1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 224, 178)), "New password", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Trebuchet MS", 0, 18), new java.awt.Color(255, 224, 178))); // NOI18N
        add(senha1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 190, 236, -1));

        senha2.setBackground(new java.awt.Color(255, 152, 0));
        senha2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        senha2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 224, 178)), "New password again", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Trebuchet MS", 0, 18), new java.awt.Color(255, 224, 178))); // NOI18N
        senha2.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                senha2CaretUpdate(evt);
            }
        });
        senha2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                senha2ActionPerformed(evt);
            }
        });
        add(senha2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 260, 236, -1));

        msg.setBackground(java.awt.Color.white);
        msg.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        add(msg, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 310, 236, 23));

        txtsenhaatual.setBackground(new java.awt.Color(255, 152, 0));
        txtsenhaatual.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtsenhaatual.setForeground(new java.awt.Color(255, 255, 255));
        txtsenhaatual.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 224, 178)), "Your current password", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Trebuchet MS", 0, 18), new java.awt.Color(255, 224, 178))); // NOI18N
        add(txtsenhaatual, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 100, 236, -1));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/senha.png"))); // NOI18N
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 350, 180, -1));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Change the password");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 40, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void senha2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_senha2ActionPerformed

    }//GEN-LAST:event_senha2ActionPerformed

    private void senha2CaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_senha2CaretUpdate
        if (senha1.getText().isEmpty() || senha2.getText().isEmpty()) {

        } else {
            String mensagem1 = null, mensagem2 = null;
            
                mensagem1 = "*Passwords match*";
                mensagem2 = "*Passwords do not match*";
            
            if (senha1.getText().equals(senha2.getText())) {
                senhacerta = true;
                msg.setForeground(new java.awt.Color(0, 153, 0));
                msg.setText(mensagem1);
            } else {
                senhacerta = false;
                msg.setForeground(new java.awt.Color(255, 0, 0));
                msg.setText(mensagem2);
            }
        }
    }//GEN-LAST:event_senha2CaretUpdate

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       if (senha1.getText().equals(senha2.getText())) {
                senhacerta = true;
            } if (senha1.getText().isEmpty() || senha2.getText().isEmpty() || txtsenhaatual.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Preencha todos os campos!");
        } else {
            if (senha1.getText().length() < 10 || senha1.getText().length() > 25 || senha2.getText().length() < 10 || senha2.getText().length() > 25) {
                
                    JOptionPane.showMessageDialog(null, "Your password must contain between 10 and 25 characters", "", JOptionPane.PLAIN_MESSAGE);
            } else {
                if (senhacerta == false) {
                        JOptionPane.showMessageDialog(null, "Passwords do not match", "", JOptionPane.PLAIN_MESSAGE);
                    
                } else {
                    System.out.println("entrou");
                    UsuarioDAO.verificartroca();
                }
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton jButton1;
    public static javax.swing.JLabel jLabel1;
    public static javax.swing.JLabel msg;
    public static javax.swing.JPasswordField senha1;
    public static javax.swing.JPasswordField senha2;
    public static javax.swing.JPasswordField txtsenhaatual;
    // End of variables declaration//GEN-END:variables
}
