/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VIEW.PAINEIS;

import VIEW.HomeAdmin;

/**
 *
 * @author Danilo
 */
public class PainelConfig extends javax.swing.JPanel {

    /**
     * Creates new form Config
     */
    public PainelConfig() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_options = new javax.swing.JPanel();
        jlabel_Title = new javax.swing.JLabel();
        jButton_novasenha = new javax.swing.JButton();
        jButton_usuarios = new javax.swing.JButton();
        jlabel_title2 = new javax.swing.JLabel();
        jlabel_title3 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 152, 0));

        jPanel_options.setBackground(new java.awt.Color(245, 124, 0));
        jPanel_options.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)), "Choice", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Trebuchet MS", 0, 14), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel_options.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlabel_Title.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jlabel_Title.setForeground(new java.awt.Color(255, 255, 255));
        jlabel_Title.setText("Options");
        jPanel_options.add(jlabel_Title, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, -1, -1));

        jButton_novasenha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/senha_1.png"))); // NOI18N
        jButton_novasenha.setBorderPainted(false);
        jButton_novasenha.setContentAreaFilled(false);
        jButton_novasenha.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_novasenha.setMaximumSize(new java.awt.Dimension(100, 100));
        jButton_novasenha.setMinimumSize(new java.awt.Dimension(100, 100));
        jButton_novasenha.setPreferredSize(new java.awt.Dimension(100, 100));
        jButton_novasenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_novasenhaActionPerformed(evt);
            }
        });
        jPanel_options.add(jButton_novasenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, -1, -1));

        jButton_usuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/detalhe.png"))); // NOI18N
        jButton_usuarios.setBorderPainted(false);
        jButton_usuarios.setContentAreaFilled(false);
        jButton_usuarios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_usuarios.setMaximumSize(new java.awt.Dimension(100, 100));
        jButton_usuarios.setMinimumSize(new java.awt.Dimension(100, 100));
        jButton_usuarios.setPreferredSize(new java.awt.Dimension(100, 100));
        jButton_usuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_usuariosActionPerformed(evt);
            }
        });
        jPanel_options.add(jButton_usuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 100, -1, -1));

        jlabel_title2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jlabel_title2.setForeground(new java.awt.Color(255, 255, 255));
        jlabel_title2.setText("View requests");
        jPanel_options.add(jlabel_title2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 190, -1, -1));

        jlabel_title3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jlabel_title3.setForeground(new java.awt.Color(255, 255, 255));
        jlabel_title3.setText("New password");
        jPanel_options.add(jlabel_title3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 190, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(146, 146, 146)
                .addComponent(jPanel_options, javax.swing.GroupLayout.PREFERRED_SIZE, 441, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(143, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(jPanel_options, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(89, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_novasenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_novasenhaActionPerformed
        HomeAdmin.PainelCard.removeAll();
        HomeAdmin.PainelCard.add(new PainelTrocarSenha());
        HomeAdmin.PainelCard.validate();
        HomeAdmin.PainelCard.repaint();

    }//GEN-LAST:event_jButton_novasenhaActionPerformed

    private void jButton_usuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_usuariosActionPerformed
       HomeAdmin.PainelCard.removeAll();
        HomeAdmin.PainelCard.add(new PainelUsuarios());
        HomeAdmin.PainelCard.validate();
        HomeAdmin.PainelCard.repaint();
    }//GEN-LAST:event_jButton_usuariosActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_novasenha;
    private javax.swing.JButton jButton_usuarios;
    private javax.swing.JPanel jPanel_options;
    private javax.swing.JLabel jlabel_Title;
    private javax.swing.JLabel jlabel_title2;
    private javax.swing.JLabel jlabel_title3;
    // End of variables declaration//GEN-END:variables
}
