/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VIEW.PAINEIS;

import static DAO.DevUtilidadesDAO.AtualizarPedidos;
import DAO.MetodosTabelaDev;
import static DAO.MetodosTabelaDev.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Danilo
 */
public class PainelUsuarios extends javax.swing.JPanel {

    /**
     * Creates new form PainelUsuarios
     */
    public PainelUsuarios() {
        initComponents();
        PainelUsuarios.TabelaUsuario.getColumnModel().getColumn(0).setPreferredWidth(20);
        PainelUsuarios.TabelaUsuario.getColumnModel().getColumn(1).setPreferredWidth(90);
        PainelUsuarios.TabelaUsuario.getColumnModel().getColumn(2).setPreferredWidth(90);
        PainelUsuarios.TabelaUsuario.getColumnModel().getColumn(4).setPreferredWidth(250);
        PainelUsuarios.TabelaUsuario.getColumnModel().getColumn(5).setPreferredWidth(20);
        MetodosTabelaDev.readJTableForDesc("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tornaradmin = new javax.swing.JButton();
        txtBuscaDesc = new javax.swing.JTextField();
        removerusuario = new javax.swing.JButton();
        solicitacoes = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        TabelaUsuario = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 152, 0));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tornaradmin.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tornaradmin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/admin.png"))); // NOI18N
        tornaradmin.setBorderPainted(false);
        tornaradmin.setContentAreaFilled(false);
        tornaradmin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tornaradmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tornaradminActionPerformed(evt);
            }
        });
        add(tornaradmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 40, 110, -1));

        txtBuscaDesc.setBackground(new java.awt.Color(255, 152, 0));
        txtBuscaDesc.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtBuscaDesc.setForeground(new java.awt.Color(255, 255, 255));
        txtBuscaDesc.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 224, 178), 1, true), "Search", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Trebuchet MS", 0, 14), new java.awt.Color(255, 224, 178))); // NOI18N
        txtBuscaDesc.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtBuscaDescCaretUpdate(evt);
            }
        });
        txtBuscaDesc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtBuscaDescMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtBuscaDescMouseExited(evt);
            }
        });
        txtBuscaDesc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscaDescActionPerformed(evt);
            }
        });
        add(txtBuscaDesc, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, 210, 40));

        removerusuario.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        removerusuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/remover.png"))); // NOI18N
        removerusuario.setBorderPainted(false);
        removerusuario.setContentAreaFilled(false);
        removerusuario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        removerusuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removerusuarioActionPerformed(evt);
            }
        });
        add(removerusuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 40, 90, -1));

        solicitacoes.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        solicitacoes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/usuario_1.png"))); // NOI18N
        solicitacoes.setBorderPainted(false);
        solicitacoes.setContentAreaFilled(false);
        solicitacoes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        solicitacoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                solicitacoesActionPerformed(evt);
            }
        });
        add(solicitacoes, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 40, 50, -1));

        jScrollPane5.setBackground(new java.awt.Color(0, 153, 255));
        jScrollPane5.setBorder(null);
        jScrollPane5.setMaximumSize(new java.awt.Dimension(680, 270));
        jScrollPane5.setMinimumSize(new java.awt.Dimension(680, 270));
        jScrollPane5.setPreferredSize(new java.awt.Dimension(680, 270));

        TabelaUsuario.setBackground(new java.awt.Color(255, 224, 178));
        TabelaUsuario.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        TabelaUsuario.setForeground(new java.awt.Color(245, 124, 0));
        TabelaUsuario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "User", "Name", "Email", "Password", "Type"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TabelaUsuario.setFocusCycleRoot(true);
        TabelaUsuario.setGridColor(new java.awt.Color(0, 102, 102));
        TabelaUsuario.setRowSelectionAllowed(false);
        TabelaUsuario.setShowHorizontalLines(false);
        TabelaUsuario.setShowVerticalLines(false);
        TabelaUsuario.getTableHeader().setReorderingAllowed(false);
        TabelaUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabelaUsuarioMouseClicked(evt);
            }
        });
        TabelaUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TabelaUsuarioKeyReleased(evt);
            }
        });
        jScrollPane5.setViewportView(TabelaUsuario);

        add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 710, 300));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Options");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 10, 80, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void tornaradminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tornaradminActionPerformed

        if (PainelUsuarios.TabelaUsuario.getSelectedRow() == -1) {
           
                JOptionPane.showMessageDialog(null, "Select a record at least", "", JOptionPane.ERROR_MESSAGE);
            
        } else {

            try {
                Object id = PainelUsuarios.TabelaUsuario.getValueAt(PainelUsuarios.TabelaUsuario.getSelectedRow(), 0);

                MudarTipo(2, id);
            } catch (Exception e) {

            }

            MetodosTabelaDev.readJTableForDesc("");
            validate();
            repaint();
        }
    }//GEN-LAST:event_tornaradminActionPerformed

    private void txtBuscaDescCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtBuscaDescCaretUpdate
        if (txtBuscaDesc.getText().isEmpty()) {

        } else {

            MetodosTabelaDev.readJTableForDesc(txtBuscaDesc.getText());
            validate();
            repaint();
        }
        while (PainelUsuarios.TabelaUsuario.getRowCount() == 0) {
            DefaultTableModel modelo = (DefaultTableModel) PainelUsuarios.TabelaUsuario.getModel();
            modelo.addRow(new Object[]{
                "-",
                "- - -",
                "- - -",
                "- - -",
                "- - -",
                "- - -",});
        }
        if (txtBuscaDesc.getText().isEmpty()) {
            MetodosTabelaDev.readJTableForDesc("");
            validate();
            repaint();
        }
    }//GEN-LAST:event_txtBuscaDescCaretUpdate

    private void txtBuscaDescMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtBuscaDescMouseClicked

    }//GEN-LAST:event_txtBuscaDescMouseClicked

    private void txtBuscaDescMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtBuscaDescMouseExited

    }//GEN-LAST:event_txtBuscaDescMouseExited

    private void txtBuscaDescActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscaDescActionPerformed
        MetodosTabelaDev.readJTableForDesc("");
    }//GEN-LAST:event_txtBuscaDescActionPerformed

    private void removerusuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removerusuarioActionPerformed

        if (PainelUsuarios.TabelaUsuario.getSelectedRow() == -1) {
           
                JOptionPane.showMessageDialog(null, "Select a record at least", "Could not delete", JOptionPane.ERROR_MESSAGE);
            
        } else {

            try {
                Object id = PainelUsuarios.TabelaUsuario.getValueAt(PainelUsuarios.TabelaUsuario.getSelectedRow(), 0);

                DeletarUsuario((int) id);
            } catch (Exception e) {

            }

        }

        MetodosTabelaDev.readJTableForDesc("");
        validate();
        repaint();
    }//GEN-LAST:event_removerusuarioActionPerformed

    private void solicitacoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_solicitacoesActionPerformed
        AtualizarPedidos();
    }//GEN-LAST:event_solicitacoesActionPerformed

    private void TabelaUsuarioKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TabelaUsuarioKeyReleased
        // TOD
    }//GEN-LAST:event_TabelaUsuarioKeyReleased

    private void TabelaUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabelaUsuarioMouseClicked
        validate();
        repaint();
    }//GEN-LAST:event_TabelaUsuarioMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JTable TabelaUsuario;
    public static javax.swing.JLabel jLabel1;
    public static javax.swing.JScrollPane jScrollPane5;
    public static javax.swing.JButton removerusuario;
    public static javax.swing.JButton solicitacoes;
    public static javax.swing.JButton tornaradmin;
    public static javax.swing.JTextField txtBuscaDesc;
    // End of variables declaration//GEN-END:variables
}
