/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VIEW;

import DAO.*;
import DAO.CadastroDAO.*;
import java.awt.Image;
import java.awt.Toolkit;
import java.net.URL;
import javax.swing.JOptionPane;

/**
 *
 * @author Thais
 */
public class TelaCadastro extends javax.swing.JFrame {

    boolean senhacerta = false;

    /**
     * Creates new form TelaLogin
     */
    public TelaCadastro() {
        initComponents();
        try {
            URL url = this.getClass().getResource("/Imagens/icone.png");
            Image imagemTitulo = Toolkit.getDefaultToolkit().getImage(url);
            setIconImage(imagemTitulo);
        } catch (Exception e) {
            System.out.println(e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtnome = new javax.swing.JTextField();
        txtusuario = new javax.swing.JTextField();
        txtemail = new javax.swing.JTextField();
        txtsenha1 = new javax.swing.JPasswordField();
        msg = new javax.swing.JLabel();
        txtsenha = new javax.swing.JPasswordField();
        btLogin = new javax.swing.JButton();
        btSalvar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 152, 0));
        jPanel1.setForeground(new java.awt.Color(255, 224, 178));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtnome.setBackground(new java.awt.Color(255, 152, 0));
        txtnome.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtnome.setForeground(new java.awt.Color(255, 255, 255));
        txtnome.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 224, 178), 1, true), "Name", javax.swing.border.TitledBorder.LEADING, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Trebuchet MS", 0, 18), new java.awt.Color(255, 224, 178))); // NOI18N
        jPanel1.add(txtnome, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 130, 259, 50));

        txtusuario.setBackground(new java.awt.Color(255, 152, 0));
        txtusuario.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtusuario.setForeground(new java.awt.Color(255, 255, 255));
        txtusuario.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 224, 178), 1, true), "User", javax.swing.border.TitledBorder.LEADING, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Trebuchet MS", 0, 18), new java.awt.Color(255, 224, 178))); // NOI18N
        jPanel1.add(txtusuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 210, 259, 50));

        txtemail.setBackground(new java.awt.Color(255, 152, 0));
        txtemail.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtemail.setForeground(new java.awt.Color(255, 255, 255));
        txtemail.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 224, 178), 1, true), "Email", javax.swing.border.TitledBorder.LEADING, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Trebuchet MS", 0, 18), new java.awt.Color(255, 224, 178))); // NOI18N
        jPanel1.add(txtemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 290, 259, 50));

        txtsenha1.setBackground(new java.awt.Color(255, 152, 0));
        txtsenha1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtsenha1.setForeground(new java.awt.Color(255, 255, 255));
        txtsenha1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 224, 178), 1, true), "Repeat password", javax.swing.border.TitledBorder.LEADING, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Trebuchet MS", 0, 18), new java.awt.Color(255, 224, 178))); // NOI18N
        txtsenha1.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtsenha1CaretUpdate(evt);
            }
        });
        jPanel1.add(txtsenha1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 240, 259, 50));

        msg.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        msg.setForeground(new java.awt.Color(0, 153, 0));
        msg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        msg.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(msg, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 290, 260, 30));

        txtsenha.setBackground(new java.awt.Color(255, 152, 0));
        txtsenha.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtsenha.setForeground(new java.awt.Color(255, 255, 255));
        txtsenha.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 224, 178), 1, true), "Password", javax.swing.border.TitledBorder.LEADING, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Trebuchet MS", 0, 18), new java.awt.Color(255, 224, 178))); // NOI18N
        jPanel1.add(txtsenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 160, 259, 50));

        btLogin.setBackground(new java.awt.Color(0, 0, 0,0));
        btLogin.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        btLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/voltar.png"))); // NOI18N
        btLogin.setContentAreaFilled(false);
        btLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btLogin.setDefaultCapable(false);
        btLogin.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btLogin.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btLogin.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        btLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLoginActionPerformed(evt);
            }
        });
        jPanel1.add(btLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 410, 70, 70));

        btSalvar.setBackground(new java.awt.Color(0, 0, 0,0));
        btSalvar.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        btSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/novousuario_1.png"))); // NOI18N
        btSalvar.setBorderPainted(false);
        btSalvar.setContentAreaFilled(false);
        btSalvar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btSalvar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btSalvar.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btSalvar.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        btSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalvarActionPerformed(evt);
            }
        });
        jPanel1.add(btSalvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 420, 70, 60));

        jPanel2.setBackground(new java.awt.Color(245, 124, 0));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(245, 124, 0));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/logout.png"))); // NOI18N
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 0, 40, 30));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 860, 30));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 28)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Register");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 100, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 860, 490));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtsenha1CaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtsenha1CaretUpdate
        if (txtsenha1.getText().isEmpty() || txtsenha.getText().isEmpty()) {

        } else {
            String mensagem1 = null, mensagem2 = null;

            mensagem1 = "*Passwords match*";
            mensagem2 = "*Passwords do not match*";

            if (txtsenha1.getText().equals(txtsenha.getText())) {
                senhacerta = true;
                msg.setForeground(new java.awt.Color(0, 153, 0));
                msg.setText(mensagem1);
            } else {
                senhacerta = false;
                msg.setForeground(new java.awt.Color(255, 0, 0));
                msg.setText(mensagem2);
            }
        }
    }//GEN-LAST:event_txtsenha1CaretUpdate

    private void btLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLoginActionPerformed
        new TelaLogin().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btLoginActionPerformed

    private void btSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalvarActionPerformed
        if (txtsenha.getText().isEmpty() || (txtsenha1.getText().isEmpty())) {

        } else {
            String mensagem1 = null, mensagem2 = null;

            mensagem1 = "*As senhas coincidem*";
            mensagem2 = "*As senhas não coincidem*";

            if (txtsenha.getText().equals(txtsenha1.getText())) {
                senhacerta = true;
                msg.setForeground(new java.awt.Color(0, 153, 0));
                msg.setText(mensagem1);
            } else {
                senhacerta = false;
                msg.setForeground(new java.awt.Color(255, 0, 0));
                msg.setText(mensagem2);
            }
        }
        if (txtnome.getText().isEmpty() || txtsenha.getText().isEmpty() || txtsenha1.getText().isEmpty() || txtemail.getText().isEmpty() || txtusuario.getText().isEmpty()) {

            JOptionPane.showMessageDialog(null, "All fields must be filled", "", JOptionPane.PLAIN_MESSAGE);

        } else {

            if (txtusuario.getText().length() < 6 || txtusuario.getText().length() > 14) {

                JOptionPane.showMessageDialog(null, "Your username must contain between 6 and 14 characters", "", JOptionPane.PLAIN_MESSAGE);

            } else {
                if (txtsenha.getText().length() < 6 || txtsenha.getText().length() > 25) {

                    JOptionPane.showMessageDialog(null, "Your password must contain between 6 and 25 characters", "", JOptionPane.PLAIN_MESSAGE);

                } else {

                    if (txtnome.getText().length() > 254) {

                        JOptionPane.showMessageDialog(null, "Very Large Name", "", JOptionPane.PLAIN_MESSAGE);

                    } else {
                        if (txtemail.getText().length() > 254) {

                            JOptionPane.showMessageDialog(null, "Very Large Email", "", JOptionPane.PLAIN_MESSAGE);

                        } else {
                            if (ValidarNome(txtnome.getText().trim()) == false) {

                                JOptionPane.showMessageDialog(null, "Name can only have letters", "", JOptionPane.PLAIN_MESSAGE);

                            } else {
                                if ((ValidarEmail(txtemail.getText())) == false) {

                                    JOptionPane.showMessageDialog(null, "Invalid Email", "", JOptionPane.PLAIN_MESSAGE);

                                } else {

                                    if (senhacerta == true) {
                                        Basica.SetUsuario(txtnome.getText(), txtusuario.getText(), txtsenha.getText(), txtemail.getText());
                                        DAO.CadastroDAO.validacao_nickname(txtusuario.getText());
                                    } else {

                                        JOptionPane.showMessageDialog(null, "Passwords do not match", "", JOptionPane.PLAIN_MESSAGE);

                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
        /*   if (txtsenha.getText().isEmpty() || (txtsenha1.getText().isEmpty())) {

        } else {
            if (txtsenha.getText().equals(txtsenha1.getText())) {
                senhacerta = true;
                msg.setForeground(new java.awt.Color(0, 153, 0));
                msg.setText("*Passwords match*");
            } else {
                senhacerta = false;
                msg.setForeground(new java.awt.Color(255, 0, 0));
                msg.setText("*Passwords do not match*");
            }
        }
        if (senhacerta == true) {
            Basica.SetUsuario(txtnome.getText(), txtusuario.getText(), txtsenha.getText(), txtemail.getText());

        } else {
            if ((ValidarEmail(txtemail.getText())) == false) {

                JOptionPane.showMessageDialog(null, "Invalid Email", "", JOptionPane.PLAIN_MESSAGE);

            } else {
                if (ValidarNome(txtnome.getText().trim()) == false) {

                    JOptionPane.showMessageDialog(null, "Name can only have letters", "", JOptionPane.PLAIN_MESSAGE);
                } else {
                    if (txtsenha.getText().length() < 6 || txtsenha.getText().length() > 25) {
                        JOptionPane.showMessageDialog(null, "Your password must contain between 6 and 25 characters", "", JOptionPane.PLAIN_MESSAGE);
                    } else {

                        if (txtusuario.getText().length() < 6 || txtusuario.getText().length() > 25) {
                            JOptionPane.showMessageDialog(null, "Your nickname must contain between 6 and 25 characters", "", JOptionPane.PLAIN_MESSAGE);
                        } else {

                            if (txtemail.getText().length() < 6 || txtemail.getText().length() > 25) {
                                JOptionPane.showMessageDialog(null, "Your email must be up to 254 characters only", "", JOptionPane.PLAIN_MESSAGE);
                            } else {
                                System.out.println("cadastro");
                                CadastroDAO.validacao_nickname(txtusuario.getText());
                            }
                        }
                    }
                }
            }
        }
         */

    }//GEN-LAST:event_btSalvarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton btLogin;
    public static javax.swing.JButton btSalvar;
    public static javax.swing.JButton jButton1;
    public static javax.swing.JLabel jLabel1;
    public static javax.swing.JPanel jPanel1;
    public static javax.swing.JPanel jPanel2;
    public static javax.swing.JLabel msg;
    public static javax.swing.JTextField txtemail;
    public static javax.swing.JTextField txtnome;
    public static javax.swing.JPasswordField txtsenha;
    public static javax.swing.JPasswordField txtsenha1;
    public static javax.swing.JTextField txtusuario;
    // End of variables declaration//GEN-END:variables
private static boolean ValidarNome(String nome) {
        boolean letra;
        letra = (nome.matches("[A-Z a-z Çç]{" + nome.length() + "}"));
        return letra;

    }

    private static boolean ValidarEmail(String email) {
        boolean emailcerto;
        emailcerto = (email.indexOf("@") > 0 && email.contains(".") && !email.contains("@."));
        return emailcerto;

    }
}
