/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VIEW;

import DAO.UsuarioDAO;
import static DAO.UtilidadesDAO.PreCarregamento;
import java.awt.*;
import java.net.URL;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author Thais
 */
public class TelaLogin extends javax.swing.JFrame {

    /**
     * Creates new form TelaLogin
     */
    public TelaLogin() {
        initComponents();
        PreCarregamento();
        
        try {
            URL url = this.getClass().getResource("/Imagens/icone.png");
            Image imagemTitulo = Toolkit.getDefaultToolkit().getImage(url);
            setIconImage(imagemTitulo);
        } catch (Exception e) {
            System.out.println(e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpainel_background = new javax.swing.JPanel();
        jpainel_menu = new javax.swing.JPanel();
        jbutton_exit = new javax.swing.JButton();
        jlabel_icon = new javax.swing.JLabel();
        jlabel_1 = new javax.swing.JLabel();
        txtusuario = new javax.swing.JTextField();
        separator1 = new javax.swing.JSeparator();
        jlabel_2 = new javax.swing.JLabel();
        separator2 = new javax.swing.JSeparator();
        jbutton_login = new javax.swing.JButton();
        jlabel_3 = new javax.swing.JLabel();
        jlabel_4 = new javax.swing.JLabel();
        jbutton_cadastrer = new javax.swing.JButton();
        txtsenha = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jpainel_background.setBackground(new java.awt.Color(255, 152, 0));
        jpainel_background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jpainel_menu.setBackground(new java.awt.Color(245, 124, 0));
        jpainel_menu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jbutton_exit.setBackground(new java.awt.Color(245, 124, 0));
        jbutton_exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/logout.png"))); // NOI18N
        jbutton_exit.setBorderPainted(false);
        jbutton_exit.setContentAreaFilled(false);
        jbutton_exit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbutton_exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbutton_exitActionPerformed(evt);
            }
        });
        jpainel_menu.add(jbutton_exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 0, 40, 30));

        jpainel_background.add(jpainel_menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, 30));

        jlabel_icon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlabel_icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/usuarioicon.png"))); // NOI18N
        jpainel_background.add(jlabel_icon, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 850, 120));

        jlabel_1.setBackground(new java.awt.Color(255, 224, 178));
        jlabel_1.setFont(new java.awt.Font("Trebuchet MS", 0, 26)); // NOI18N
        jlabel_1.setForeground(new java.awt.Color(255, 224, 178));
        jlabel_1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlabel_1.setText("Login");
        jpainel_background.add(jlabel_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 830, 40));

        txtusuario.setBackground(new java.awt.Color(255, 152, 0));
        txtusuario.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        txtusuario.setForeground(new java.awt.Color(255, 255, 255));
        txtusuario.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtusuario.setBorder(null);
        jpainel_background.add(txtusuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 210, 150, 30));

        separator1.setForeground(new java.awt.Color(255, 255, 255));
        jpainel_background.add(separator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 250, 150, 10));

        jlabel_2.setBackground(new java.awt.Color(255, 224, 178));
        jlabel_2.setFont(new java.awt.Font("Trebuchet MS", 0, 26)); // NOI18N
        jlabel_2.setForeground(new java.awt.Color(255, 224, 178));
        jlabel_2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlabel_2.setText("Password");
        jpainel_background.add(jlabel_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 830, 40));

        separator2.setForeground(new java.awt.Color(255, 255, 255));
        jpainel_background.add(separator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 350, 150, 10));

        jbutton_login.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/entrar.png"))); // NOI18N
        jbutton_login.setBorderPainted(false);
        jbutton_login.setContentAreaFilled(false);
        jbutton_login.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbutton_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbutton_loginActionPerformed(evt);
            }
        });
        jpainel_background.add(jbutton_login, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 410, -1, -1));

        jlabel_3.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jlabel_3.setForeground(new java.awt.Color(255, 255, 255));
        jlabel_3.setText("Want to access our system?");
        jpainel_background.add(jlabel_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 410, -1, -1));

        jlabel_4.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jlabel_4.setForeground(new java.awt.Color(255, 255, 255));
        jlabel_4.setText(" Register");
        jpainel_background.add(jlabel_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 440, -1, -1));

        jbutton_cadastrer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/novousuario.png"))); // NOI18N
        jbutton_cadastrer.setBorderPainted(false);
        jbutton_cadastrer.setContentAreaFilled(false);
        jbutton_cadastrer.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbutton_cadastrer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbutton_cadastrerActionPerformed(evt);
            }
        });
        jpainel_background.add(jbutton_cadastrer, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 430, 60, 40));

        txtsenha.setBackground(new java.awt.Color(255, 152, 0));
        txtsenha.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        txtsenha.setForeground(new java.awt.Color(255, 255, 255));
        txtsenha.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtsenha.setBorder(null);
        jpainel_background.add(txtsenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 310, 150, 30));

        getContentPane().add(jpainel_background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, 490));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jbutton_exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbutton_exitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jbutton_exitActionPerformed

    private void jbutton_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbutton_loginActionPerformed

        if (txtsenha.getText().isEmpty() || txtusuario.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "All fields must be filled!", "", JOptionPane.PLAIN_MESSAGE);
        } else {
            boolean livre = UsuarioDAO.validacao_login();
            if(livre==true){
                new HomeAdmin().setVisible(true);
                this.dispose();
            }else{
                TelaLogin.txtsenha.setText(null);
                TelaLogin.txtusuario.setText(null);
                JOptionPane.showMessageDialog(null, "Incorrect user or password\nor you have not yet been\n accepted into the system", "", JOptionPane.PLAIN_MESSAGE);
            }
        }
    }//GEN-LAST:event_jbutton_loginActionPerformed

    private void jbutton_cadastrerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbutton_cadastrerActionPerformed
        new TelaCadastro().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jbutton_cadastrerActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton jbutton_cadastrer;
    public static javax.swing.JButton jbutton_exit;
    public static javax.swing.JButton jbutton_login;
    public static javax.swing.JLabel jlabel_1;
    public static javax.swing.JLabel jlabel_2;
    public static javax.swing.JLabel jlabel_3;
    public static javax.swing.JLabel jlabel_4;
    public static javax.swing.JLabel jlabel_icon;
    public static javax.swing.JPanel jpainel_background;
    public static javax.swing.JPanel jpainel_menu;
    public static javax.swing.JSeparator separator1;
    public static javax.swing.JSeparator separator2;
    public static javax.swing.JPasswordField txtsenha;
    public static javax.swing.JTextField txtusuario;
    // End of variables declaration//GEN-END:variables
}
